### PR TITLE
Added is_valid_language_code to check code validity without raising an exception

### PR DESCRIPTION
**Pull request by yaniv-golan**
Added is_valid_language_code to check code validity without raising an exception.

It uses a cached, threadsafe copy of the data from iter_langs. 

Updated tests and README.md as well.

### CODE REVIEW

**Comment by LBeaudoux** [comment]
For a language checker function to be added to this library, it would have to support any combination of  language identifiers or language names. I suggest we take inspiration from the built-in function [`isinstance`](https://docs.python.org/3/library/functions.html#isinstance):

```python
>>> is_language("fr", "pt1")
True
>>> is_language("fra", ("pt1", "pt2b", "pt2t", "pt3"))
True
>>> is_language("French", ("name", "other_names"))
True
```

**Comment by yaniv-golan** [comment]
> Thank you Yaniv for taking the time to contribute to this library.
> 
> Could you please tell us a little more about the use case that led you to propose this feature? In particular, why are you trying to avoid raising exceptions?

Thank you for your prompt response and for considering my contribution.

The main use case for proposing the is_valid_language_code function is to facilitate straightforward validation of language codes in applications where handling exceptions might not be practical or desired. In scenarios such as user input validation, data cleaning, or processing large datasets, it's often more efficient to have a simple boolean check rather than wrapping code in try-except blocks to handle exceptions.

By providing a function that returns True or False, developers can easily integrate language code validation into conditional statements, form validations, or data pipelines without interrupting the flow of the program. This approach improves code readability and maintainability, especially when the goal is simply to confirm the validity of a code rather than to create a Lang instance or handle exceptions.

**Comment by yaniv-golan** [comment]
> For a language checker to be added to this library, it would have to support any combination of language identifiers or language names. I suggest we take inspiration from the built-in function [`isinstance`](https://docs.python.org/3/library/functions.html#isinstance):
> 
> ```python
> >>> is_language("fr", "pt1")
> True
> >>> is_language("fra", ("pt1", "pt2b", "pt2t", "pt3"))
> True
> >>> is_language("French", ("name", "other_name"))
> True
> ```

**Answer to Response #2:**

Thank you for the excellent suggestion. I agree that adopting an `is_language` function similar to `isinstance` would enhance the library's flexibility. Here's an implementation that supports checking any combination of language identifiers or names without using exceptions:

```python
def is_language(
    value: str,
    tags: Union[str, Tuple[str, ...]] = ("pt1", "pt2b", "pt2t", "pt3", "pt5", "name", "other_name")
) -> bool:
    """Check if a given value corresponds to a valid language identifier or name.

    Parameters
    ----------
    value : str
        The language identifier or name to validate.
    tags : Union[str, Tuple[str, ...]], optional
        The ISO 639 tags or names to check against. Defaults to all available tags.

    Returns
    -------
    bool
        True if the value is valid for the given tags, False otherwise.
    """
    if isinstance(tags, str):
        tags = (tags,)

    for tag in tags:
        lang_tuple = Lang._get_language_tuple(tag, value)
        if lang_tuple:
            return True
    return False
```

Using this function: 

```python
print(is_language("fr", "pt1"))  # Output: True
print(is_language("fra", ("pt1", "pt2b", "pt2t", "pt3")))  # Output: True
print(is_language("French", ("name", "other_name")))  # Output: True
print(is_language("xyz"))  # Output: False
```

WDYT?

**Comment by LBeaudoux** [comment]
> WDYT?

Thank you. I think we're making progress!

However, I would prefer this validator not to be built on top of the `Lang` class, but to load the underlying JSON mappings directly. 

I would also like to use 'representation' rather than 'tag' as this term appears in the [ISO 639 homepage](https://www.iso.org/iso-639-language-code).

```python
@lru_cache
def _get_language_values(representations: Tuple[str]) -> Set[str]:
    representations = set(representations)
    all_representations = {
        "pt1",
        "pt2b",
        "pt2t",
        "pt3",
        "pt5",
        "name",
        "other_name",
    }
    if representations - all_representations:
        raise ValueError

    language_values = set()
    if "other_name" in representations:
        mapping = load_file("mapping_ref_name")
        language_values.update(mapping.keys())
        representations.remove("other_name")
    if representations:
        mapping = load_file("mapping_data")
        for r in representations:
            language_values.update(mapping[r].keys())

    return language_values


def is_language(
    value: str,
    representations: Union[str, Tuple[str, ...]] = (
        "pt1",
        "pt2b",
        "pt2t",
        "pt3",
        "pt5",
        "name",
        "other_name",
    ),
) -> bool:
    """Check if a given value corresponds to a valid ISO 639 language
    identifier or name.

    Parameters
    ----------
    value : str
        The language identifier or name to validate.
    representations : Union[str, Tuple[str, ...]], optional
        The ISO 639 language representations to check against. Defaults to all.

    Returns
    -------
    bool
        True if the value is valid for the given language representations,
        False otherwise.
    """
    if isinstance(representations, str):
        representations = (representations,)

    if not isinstance(representations, tuple):
        raise TypeError

    return value in _get_language_values(representations)

```

And here are some examples of tests:

```python
  assert is_language("fr", "pt1") is True
  assert is_language("fra", ("pt1", "pt2b", "pt2t", "pt3")) is True
  assert is_language("French", ("name", "other_name")) is True
  assert is_language("fre") is True
  assert is_language("xyz") is False
  with pytest.raises(ValueError):
      is_language("fr", "foobar")
  with pytest.raises(TypeError):
      is_language("fr", 42)
```

Do you have other improvements?

**Comment by yaniv-golan** [comment]
> > WDYT?
> 
> Thank you. I think we're making progress!

Yes we are :) appreciate your patience and attention to details very much.

> 
> However, I would prefer this validator not to be built on top of the `Lang` class, but to load the underlying JSON mappings directly.
> 
> I would also like to use 'representation' rather than 'tag' as this term appears in the [ISO 639 homepage](https://www.iso.org/iso-639-language-code).
> 

I noticed that in the current library code, the term used for these language identifiers is `tags`. I understand your suggestion to change this to `representations` to align with ISO 639 terminology.

However, upon reviewing the ISO 639 standard, I've found that the term used is **'language identifiers'** or **'codes'**, rather than 'representations'. Here are some excerpts from the ISO 639 homepage:

> The ISO 639 language code comprises four sets of **language identifiers**:
>
> - Set 1: **two-letter language identifiers**...
> - Set 2: **three-letter language identifiers**...
> - Set 3: **three-letter language identifiers**...
> - Set 5: **three-letter language identifiers**...

Given this, what do you think about using the term **'identifiers'** instead? It would make the code align closely with the ISO 639 terminology and could enhance clarity for users familiar with the standard.

**Here's how it might look:**

```python
@lru_cache
def _get_language_values(identifiers: Tuple[str]) -> Set[str]:
    identifiers = set(identifiers)
    all_identifiers = {
        "pt1", "pt2b", "pt2t", "pt3", "pt5", "name", "other_name",
    }
    invalid_identifiers = identifiers - all_identifiers
    if invalid_identifiers:
        raise ValueError(
            f"Invalid identifiers: {', '.join(invalid_identifiers)}. "
            f"Valid options are: {', '.join(sorted(all_identifiers))}."
        )
    language_values = set()
    if "other_name" in identifiers:
        mapping = load_file("mapping_ref_name")
        language_values.update(mapping.keys())
        identifiers.remove("other_name")
    if identifiers:
        mapping = load_file("mapping_data")
        for idf in identifiers:
            language_values.update(mapping[idf].keys())
    return language_values

def is_language(
    value: str,
    identifiers: Union[str, Tuple[str, ...]] = (
        "pt1", "pt2b", "pt2t", "pt3", "pt5", "name", "other_name",
    ),
) -> bool:
    """Check if a given value corresponds to a valid ISO 639 language identifier or name.

    Parameters
    ----------
    value : str
        The language identifier or name to validate.
    identifiers : Union[str, Tuple[str, ...]], optional
        The ISO 639 identifiers or names to check against. Defaults to all available identifiers.

    Returns
    -------
    bool
        True if the value is valid for the given identifiers, False otherwise.
    """
    if isinstance(identifiers, str):
        identifiers = (identifiers,)
    elif isinstance(identifiers, (list, set)):
        identifiers = tuple(identifiers)
    elif not isinstance(identifiers, tuple):
        raise TypeError(
            f"'identifiers' must be a string or an iterable of strings, got {type(identifiers).__name__}"
        )
    return value in _get_language_values(identifiers)
```

Please let me know your thoughts on this adjustment. I'm happy to update the pull request with these changes.

**Comment by LBeaudoux** [comment]
> Given this, what do you think about using the term 'identifiers' instead? It would make the code align closely with the ISO 639 terminology and could enhance clarity for users familiar with the standard.

Under ISO 639, language names and language identifiers are separate things. What do you think about renaming our argument `identifiers_or_names`?

I've updated our code:
```python
@lru_cache
def _get_language_values(identifiers_or_names: Tuple[str]) -> Set[str]:
    tags = set(identifiers_or_names)
    all_tags = {"pt1", "pt2b", "pt2t", "pt3", "pt5", "name", "other_name"}
    invalid_tags = tags - all_tags
    if invalid_tags:
        raise ValueError(
            f"Invalid identifiers or names: {', '.join(invalid_tags)}. "
            f"Valid options are: {', '.join(sorted(all_tags))}."
        )
    language_values = set()
    if "other_name" in tags:
        mapping = load_file("mapping_ref_name")
        language_values.update(mapping.keys())
        tags.remove("other_name")
    if tags:
        mapping = load_file("mapping_data")
        for tag in tags:
            language_values.update(mapping[tag].keys())
    return language_values


def is_language(
    value: str,
    identifiers_or_names: Union[str, Tuple[str, ...]] = (
        "pt1",
        "pt2b",
        "pt2t",
        "pt3",
        "pt5",
        "name",
        "other_name",
    ),
) -> bool:
    """Check if a given value corresponds to a valid ISO 639 language
    identifier or name.

    Parameters
    ----------
    value : str
        The language value to validate.
    identifiers_or_names : Union[str, Tuple[str, ...]], optional
        The ISO 639 identifiers or names to check against. Defaults to all
        available identifiers and names.

    Returns
    -------
    bool
        True if the value is valid for the given identifiers and names, False
        otherwise.

    Raises
    ------
    TypeError
        When `identifiers_or_names` is not a tuple or a tuple of strings.
    ValueError
        When string(s) of `identifiers_or_names` are not 'pt1', 'pt2b', 'pt2t',
        'pt3', 'pt5', 'name' or 'other_name'.

    Examples
    --------
    >>> is_language("fr")
    True
    >>> is_language("French")
    True
    >>> is_language("fr", "pt3")
    False
    >>> is_language("fre", ("pt2b", "pt2t"))
    True
    """
    if isinstance(identifiers_or_names, str):
        identifiers_or_names = (identifiers_or_names,)
    elif isinstance(identifiers_or_names, (list, set)) and all(
        isinstance(s, str) for s in identifiers_or_names
    ):
        identifiers_or_names = tuple(identifiers_or_names)
    elif not isinstance(identifiers_or_names, tuple):
        raise TypeError(
            "'identifiers_or_names' must be a string or an iterable of "
            f"strings, got {type(identifiers_or_names).__name__}."
        )
    elif not all(isinstance(s, str) for s in identifiers_or_names):
        all_types = (type(v).__name__ for v in identifiers_or_names)
        raise TypeError(
            "'identifiers_or_names' must be a string or an iterable of "
            f"strings, got tuple of {' and '.join(all_types)}.",
        )
    return value in _get_language_values(identifiers_or_names)
```
Please feel free to update your PR with our changes. I'll add some final adjustments if necessary.

**Review by yaniv-golan — COMMENTED** [review]
Updated to is_language

**Comment by LBeaudoux** [comment]
I am finally merging the language checker. @yaniv-golan thank you for suggesting and helping to build this new feature.

**Comment by yaniv-golan** [comment]
> I am finally merging the language checker. @yaniv-golan thank you for suggesting and helping to build this new feature.

Thank you @LBeaudoux for your support and guidance, I've actually learned a lot from you throughout this process!

**Pull request merged**
